%% Malingering

clear;

sampler = 0; % Choose 0=WinBUGS, 1=JAGS

%% Data
k = [45,45,44,45,44,45,45,45,45,45,30,20,6,44,44,27,25,17,14,27,35,30]; % total correct per participant

% Constants
p = length(k); % number of participants
n = 45; % number of questions

%% Sampling
% MCMC Parameters
nchains = 2; % How Many Chains?
nburnin = 1e3; % How Many Burn-in Samples?
nsamples = 1e3;  %How Many Recorded Samples?
nthin = 1; % How Often is a Sample Recorded?
doparallel = 0; % Parallel Option

% Initial Values to Supply to WinBugs
for i=1:nchains
    S.z = round(rand(1,p));
    S.psi = [0.5 0.5];
    init0(i) = S;
end

% Assign Matlab Variables to the Observed Nodes
datastruct = struct('k',k,'p',p,'n',n);

% Sampling
if ~sampler
    % Use WinBUGS to Sample
    tic
    [samples, stats, structarray] = matbugs(datastruct, ...
        fullfile(pwd, 'Malingering_1.txt'), ...
        'init', init0, ...
        'nChains', nchains, ...
        'view',1, 'nburnin', nburnin, 'nsamples', nsamples, ...
        'thin', nthin, 'DICstatus', 0, 'refreshrate',100, ...
        'monitorParams', {'psi','z'}, ...
        'Bugdir', 'C:/Program Files/WinBUGS14');
    toc
else
    % Use JAGS to Sample
    tic
    fprintf( 'Running JAGS ...\n' );
    [samples, stats] = matjags( ...
        datastruct, ...
        fullfile(pwd, 'Malingering_1.txt'), ...
        init0, ...
        'doparallel' , doparallel, ...
        'nchains', nchains,...
        'nburnin', nburnin,...
        'nsamples', nsamples, ...
        'thin', nthin, ...
        'monitorparams', {'psi','z'}, ...
        'savejagsoutput' , 1 , ...
        'verbosity' , 1 , ...
        'cleanup' , 0 , ...
        'workingdir' , 'tmpjags' );
    toc
end;